# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'OpenCVFirstChapter-kern' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for OpenCVFirstChapter-kern
  pod 'OpenCVSource', :path => '../OpenCVSource'
    pod 'OpenCVUtils', :path => '../OpenCVUtils'
    pod 'OpenCVBase', :path => '../OpenCVBase'

  target 'OpenCVFirstChapter-kernTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenCVFirstChapter-kernUITests' do
    # Pods for testing
  end

end
