# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'OpenCVSecondChapter-bounding_rotated_ellipses' do
  # Comment the next line if you don't want to use dynamic frameworks
   pod 'OpenCVSource', :path => '../OpenCVSource'
  pod 'OpenCVUtils', :path => '../OpenCVUtils'
  pod 'OpenCVBase', :path => '../OpenCVBase'

  # Pods for OpenCVSecondChapter-bounding_rotated_ellipses

  target 'OpenCVSecondChapter-bounding_rotated_ellipsesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenCVSecondChapter-bounding_rotated_ellipsesUITests' do
    # Pods for testing
  end

end
