# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'OpenCVFirstChapter-Mat' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
  pod 'OpenCV', '3.4.6'

  pod 'OpenCVSource', :path => '../OpenCVSource'
  pod 'OpenCVUtils', :path => '../OpenCVUtils'
  pod 'OpenCVBase', :path => '../OpenCVBase'
  # Pods for OpenCVFirstChapter-Mat

  target 'OpenCVFirstChapter-MatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenCVFirstChapter-MatUITests' do
    # Pods for testing
  end

end
