# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'OpenCVFirstProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'OpenCV', '~> 3.4.2'
  # Pods for OpenCVFirstProject

  target 'OpenCVFirstProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenCVFirstProjectUITests' do
    # Pods for testing
  end

end
