# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'OpenCVSecondChapter-find_contours' do
  # Comment the next line if you don't want to use dynamic frameworks
    pod 'OpenCVSource', :path => '../OpenCVSource'
  pod 'OpenCVUtils', :path => '../OpenCVUtils'
  pod 'OpenCVBase', :path => '../OpenCVBase'

  # Pods for OpenCVSecondChapter-find_contours

  target 'OpenCVSecondChapter-find_contoursTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenCVSecondChapter-find_contoursUITests' do
    # Pods for testing
  end

end
