# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenCVSecondChapter-back_projection' do
  # Comment the next line if you don't want to use dynamic frameworks
    pod 'OpenCVSource', :path => '../OpenCVSource'
  pod 'OpenCVUtils', :path => '../OpenCVUtils'
  pod 'OpenCVBase', :path => '../OpenCVBase'

  # Pods for OpenCVSecondChapter-back_projection

  target 'OpenCVSecondChapter-back_projectionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenCVSecondChapter-back_projectionUITests' do
    # Pods for testing
  end

end
