# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'OpenCVSecondChapter-Laplace' do
  # Comment the next line if you don't want to use dynamic frameworks
   pod 'OpenCVSource', :path => '../OpenCVSource'
  pod 'OpenCVUtils', :path => '../OpenCVUtils'
  pod 'OpenCVBase', :path => '../OpenCVBase'


  # Pods for OpenCVSecondChapter-Laplace

  target 'OpenCVSecondChapter-LaplaceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenCVSecondChapter-LaplaceUITests' do
    # Pods for testing
  end

end
